// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGcfnlYkt78DrI1lYglicYHmrRk3S2lLE',
    appId: '1:369211268612:web:c5ab492c10c230d07b5f51',
    messagingSenderId: '369211268612',
    projectId: 'yep-atomi',
    authDomain: 'yep-atomi.firebaseapp.com',
    storageBucket: 'yep-atomi.firebasestorage.app',
    measurementId: 'G-GFV1KJLPLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4eim6SLvY0oFipo-FjP7U-FF85lhCnLg',
    appId: '1:369211268612:android:7b9e46d53f1bd86f7b5f51',
    messagingSenderId: '369211268612',
    projectId: 'yep-atomi',
    storageBucket: 'yep-atomi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT_wR-34un0cdreWYoPShMR4lzMs0e2Co',
    appId: '1:369211268612:ios:40ebbae998bc22bd7b5f51',
    messagingSenderId: '369211268612',
    projectId: 'yep-atomi',
    storageBucket: 'yep-atomi.firebasestorage.app',
    iosBundleId: 'com.example.atomiYep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT_wR-34un0cdreWYoPShMR4lzMs0e2Co',
    appId: '1:369211268612:ios:40ebbae998bc22bd7b5f51',
    messagingSenderId: '369211268612',
    projectId: 'yep-atomi',
    storageBucket: 'yep-atomi.firebasestorage.app',
    iosBundleId: 'com.example.atomiYep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGcfnlYkt78DrI1lYglicYHmrRk3S2lLE',
    appId: '1:369211268612:web:32fc208f96e9c81a7b5f51',
    messagingSenderId: '369211268612',
    projectId: 'yep-atomi',
    authDomain: 'yep-atomi.firebaseapp.com',
    storageBucket: 'yep-atomi.firebasestorage.app',
    measurementId: 'G-5K9E3SHXLK',
  );
}
